[env:esp32-s3-lcd-2]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
